import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.Serializable;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/** Class to hold the information for the items that are in the scenes
 * @author Jared Moore
 * @version 11/2/12
 */
public class Item implements Comparable<Item>, Serializable {

	private ImageIcon icon;
	private String name, description;
	private JLabel label;
	
	/** Constructor for Item.  Set up an Item object with the desired information
	 * @param icon The icon to be used
	 * @param nm The item's name
	 * @param des A description of the Item
	 */
	public Item(ImageIcon icon, String nm, String des) {
		this.icon = icon;
		this.name = nm;
		this.description = des;
		
		label = new JLabel(this.name);
		label.addMouseListener(new MouseAdapter() {
			
			/** Show a description of the item when it is clicked
			 * @param e The event that is generated by the click
			 */
			@Override
			public void mouseClicked(MouseEvent e) {
				JOptionPane.showMessageDialog(null, description, name, JOptionPane.PLAIN_MESSAGE);
			}
		});
	}
	
	/** Getter for the Icon
	 * @return the icon
	 */
	public ImageIcon getIcon() {
		return icon;
	}


	/** Getter for the name
	 * @return the name
	 */
	public String getName() {
		return name;
	}


	/** Getter for the description
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}


	/** Getter for the label
	 * @return the label
	 */
	public JLabel getLabel() {
		return label;
	}

	/** Compares this object to another object to see the difference
	 * @param o The item to be compared to
	 * @return The difference between the names of the objects
	 */
	@Override
	public int compareTo(Item o) {
		return (getName().compareTo(o.getName()));
	}
	
	
}
